In [1]:
import jax
import jax.numpy as jnp

In [11]:
def e(k, dim):
    """Return k'th std. basis vector in R^dim"""
    return jnp.zeros((dim,)).at[k].set(1.0)
    
def E(j, k, dim):
    """Return outer product of j'th and k'th std. basis vector in R^dim"""
    ej = e(j, dim)
    ek = e(k, dim)
    return jnp.outer(ej,ek)

D = 4
k = 3
theta = 0.22 * jnp.pi

I = jnp.eye(D)
ck = jnp.cos(theta)
sk = jnp.sin(theta)

I + (ck - 1) * (E(0,0,D) + E(k,k,D)) + sk * (E(0,k,D) - E(k,0,D))

Array([[ 0.77051324,  0.        ,  0.        ,  0.637424  ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [-0.637424  ,  0.        ,  0.        ,  0.77051324]],      dtype=float32)

In [10]:
def givens(A, B):
    r = jnp.hypot(A, B)
    c = jnp.where(r != 0.0, A / r, 1.0)
    s = jnp.where(r != 0.0, B / r, 0.0)
    return r, c, s

In [12]:
E(0,1,3)

Array([[0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [13]:
X = jnp.arange(1,31).reshape(10,3)
def matvec(v):
    return X @ v


jax.jacfwd(matvec)(jax.ones())

Array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.],
       [22., 23., 24.],
       [25., 26., 27.],
       [28., 29., 30.]], dtype=float64)

: 